### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dhilt** [khajjit/ui-scroll-1#6]
Тестировать нужно только Модуль. Тестовое Приложение не трогаем (возможно мы вообще откажемся от Приложения, выкинем его из основного репозитория или же запрячем в какой-нибудь demo-бранч). Давай рассмотрим, какие есть варианты тестирования и выберем оптимальную стратегию.

**Comment by dyuv-dev** [comment]
@dhilt Набросал немного кода в новом бранче - https://github.com/khajjit/ngx-ui-scroll/commit/f7b476ff2e1f1d905e219a12b0a087e1a163cc60, если что можно удалить этот бранч и по новой начать. Всего-навсего сделал так, чтобы спеки запускались.

1. Сами библиотеки, при помощи которых будем писать тесты, это будут karma и стандартные ангуляровские библиотеки? И все тесты мы должны прогонять исключительно через браузер с помощью karma? В коммите я позаимствовал подход из репозитория ngx-typeahead, изменения в файле karma.conf.js и новый файл ./spec.bundle.js - можно сказать, это все оттуда.

2. Тестовое приложение не трогал, но скопировал оттуда компонент (./tests/testedComponent.ts). Пока что посматриваю на следующие статьи - https://blog.thoughtram.io/angular/2016/12/27/angular-2-advance-testing-with-custom-matchers.html#testing-directives, https://codecraft.tv/courses/angular/unit-testing/directives/, https://stackoverflow.com/questions/36432407/how-to-unit-test-a-directive-in-angular-2. Буду пробовать что-нибудь сделать, отталкиваясь от них...

**Comment by dhilt** [comment]
Да, запуск (и соответственно отладка) в браузере необходимы. При удаленной сборке тоже будем гонять тесты на браузерах. В старом скроллере это так и работало, насколько ты помнишь (ты еще пофиксил запуск Chrome для Linux-систем). Главное, что тесты должны работать поверх исключительно поверх Модуля скроллера...

**Comment by dyuv-dev** [comment]
@dhilt Сейчас все вроде работает поверх модуля - https://github.com/khajjit/ngx-ui-scroll/commit/6b909848e0bd6f348e82a0b702aa7bb25bd0d714. И добавил маленький тест на то, как должен именоваться тег (правда в оригинальном репозитории он уже именуется 'ui-scroll', позже надо будет исправить..). В дальнейшем наверное попытаюсь проверить присвоились ли стили, количество сущностей внутри скролла и тому подобное - в общем всё то, что должно выполниться на этапе инициализации директивы.

**Comment by dhilt** [comment]
@khajjit Хорошо, давай тогда завтра это обсудим вместе с UiScroll Workflow. У меня есть время во второй половине дня субботы и в первой половине воскресенья. Когда есть время у тебя? Добавь меня в скайпе d.alexanov@skype и поставь https://www.teamviewer.com, может понадобится.

**Comment by dyuv-dev** [comment]
@dhilt Буду свободен и в субботу, и в воскресенье. Может в субботу тогда? А в скайпе я уже есть вроде, давным давно там созванивались командой по поводу react-try.

**Comment by dhilt** [comment]
@khajjit Я не нашел тебя у себя в контактах, будет здорово, если ты проявишься тем или иным способом, например, отправив сообщение.

**Comment by dyuv-dev** [comment]
@dhilt Разглядывая код с манипуляциями над пикселями, мне на ум вот что пришло - сейчас ведь с текущим подходом не получится в готовом приложении (на app.component.html) задать скроллеру height в процентном соотношении? Или я ошибаюсь?

**Comment by dhilt** [comment]
@khajjit Высоту viewport, я полагаю, можно регулировать различными способами. Внутри себе скроллер считает абсолютную высоту и результаты этих вычислений не будут зависеть от того, каким способом она была задана. Но надо помнить, что мы движемся в сторону большей абстракции и однажды вместо высоты сможет выступить также и ширина, когда мы дойдем до горизонтального скролла.

Та проблема, которую мы смотрели самой последней (с неправильным элементом на верхней позиции после скролла вверх), как и сотня других случаев, должна быть покрыта тестами. Тесты должны полностью описывать желаемое поведение визуальной части, а мы как бы подгоняем под это логику.

Но сейчас нам надо заставить работать sourcemaps, чтобы отладка тестов стала нормальным процессом.

**Comment by dhilt** [comment]
@khajjit Я решил взглянуть на ту проблему и понял, что проблемы нет.

![testing issue 6 khajjit_ngx-ui-scroll](https://user-images.githubusercontent.com/4365660/35194337-51ca6122-fec3-11e7-921b-fca35d8d3864.png)

Находясь в изначальной позиции (перед скроллом вверх), мы имеем всего 4 элемента над текущим верхним элементом (над 90). Это вызвано тем, что пятый был обрезан clip-процессом, при этом вместо пятого был увеличен padding-top на высоту одного вырезанного элемента. Таким образом максимальный один скролл вверх должен поднять нас на высоту 4 видимых и одного вырезанного элемента (суммарно на 90 пикселей). Что в свою очередь сделает верхним видимым элементом 85. Код работает правильно.

Поняв это однажды и написав соответствующие тесты, мы забудем об этой проблеме.

**Comment by dyuv-dev** [comment]
@dhilt Хмм, у меня вот к примеру сверху невидимыми остаются только 3 элемента.

![id87](https://user-images.githubusercontent.com/26064824/35198448-16bec9c6-ff2a-11e7-992e-0b8ca8d11221.png)

Но это такие результаты в FF. Chrome же показывает то же, что и у вас.
Я вот пробовал скроллеру задать height 100%, но к желаемому результату это не привело, скроллер впал в бесконечное пересчитывание item.

**Comment by dhilt** [comment]
@khajjit Я убежден в том, что это проблема некроссбраузерных расчетов внутри скроллера. Видишь, FF посчитал, что два вырезанных ряда имеют высоту 40px, то есть по 20px на ряд, тогда как Chrome рассчитывает по 18px на ряд. Эта разница очевидно составляет по 1 пикселю на границы каждого ряда. Это надо будет исправлять, но только после внедрения нового Workflow. Пока же надо подготовить все, чтобы после эволюции Workflow его можно было покрыть тестами достаточно быстро. Запуск тестов на тестов разных браузерах даст нам необходимый результат. В частности, мы исключим ситуацию, когда мы сделали фикс для FF и сломали Chrome; тесты сразу же скажут об этом.

**Comment by dyuv-dev** [comment]
@dhilt Посмотрел скроллер в браузере Microsoft Edge, там на ряд и вовсе приходится 18.4px. Как собственно можно приравнять ряд к одному размеру для всех браузеров? Css-атрибуты аля padding, margin, border и так изначально обозначены как 0px..

Если код в Workflow изменится, но при этом в браузере будет всё тот же вид и всё та же реакция на действия пользователя - тесты ведь не придется переписывать, у нас ведь e2e тесты. Ну или почти не придется. Тем временем добавил sourcemaps для тестов - https://github.com/khajjit/ngx-ui-scroll/commit/d3746e0aeac8a97dbffe532eea3cf0d7d27944cb.

**Comment by dyuv-dev** [comment]
@dhilt И написал немного обобщенных тестов на верстку, какие теги должны быть и с какими id, и то какие стили должны быть после инициализации - https://github.com/khajjit/ngx-ui-scroll/commit/695feab018c7072379d1d303fc534c240fa7ae58. Пока что не сильно понимаю куда двигаться дальше, но точно знаю что надо починить запуск karma - сейчас он не до конца корректно работает.

Отталкивался от официальной документации, и что-то там говорят что karma больше для юнит-тестов подходит, а protractor для e2e (https://angular.io/guide/testing#tools-and-technologies). Может быть я не в ту сторону движусь?

**Comment by dhilt** [comment]
@khajjit Высоты должны совпадать для всех браузеров, это ответственность скроллера, рассчитать все кроссбраузерно. Тесты будут одни для всех браузеров, нужно будет переписать логику внутри скроллера.

В старом скроллере все было под кармой написано и прекрасно работало, но если под протрактор проще писать и, скажем так, это больше принято, то можно попробовать его пощупать. А Карму оставить только для тестирования каких-то обособленным логических кусков...

Так или иначе от первых тестов нам нужны:

 - эмуляция событий скролла (загрузились, проскроллили на N пикселей в определенную сторону, дождались рендера, проверили DOM)
 - доступ к datasource (столько-то раз побывали в методе get, метод вызывался с такими-то параметрами)

И sourcemaps!

**Comment by dyuv-dev** [comment]
@dhilt Пока что мне кажется что и с кармой все должно отлично получиться. И несмотря на то, что в официальной документации сделаны такие разделения, в большинстве репозиториев я все же находил карму, да и собственно старый проект был сделан с кармой.

Sourcemaps уже есть. И скроллер в открывающемся окне браузера при старте кармы работает корректно без ошибок, но только при условии что в тестах будет только один it. Сейчас я на этом месте закопался, честно говоря. Нужно на beforeEach как-то обновлять директиву (как я понимаю сейчас с каждым it срабатывает ngOnInit на компоненте директивы и в Data.items скапливаются сущности - и выходит беспорядок). Сделал небольшой коммит с этим всем - https://github.com/khajjit/ngx-ui-scroll/commit/9c5673b6f5728c4f4bc158f3cedd2a7ff4ba8883.

**Comment by dhilt** [comment]
@khajjit Ага, я понимаю проблему... Я работаю в бранче [workflow-2](https://github.com/dhilt/ngx-ui-scroll/tree/workflow-2), там уже шквал апдейтов и это примерно треть от запланированного.

Можем ли мы в тестах уже подкопаться к вызовам datasource и сэмулировать событие скролла?

**Comment by dyuv-dev** [comment]
@dhilt Да, теперь можем, но криво. Сделал две спеки на единоразовый скролл вверх и вниз, коммит - https://github.com/khajjit/ngx-ui-scroll/commit/edfbd342dd51d058a466ec6fd30c62561faadddf.
Суть такова - ищем тег app-ui-scroll (1-ая строка сразу после it), далее сдвигаем ползунок в самый притык к верху или низу (3-яя строка) и иницируем вызов события scroll, который навешивается в ./src/ui-scroll.component.ts (2-ая и 4-ая). Хотя последнее действие возможно уже излишне. И все действия идут напрямую через DOM.

Только есть проблема с асинхронностью. Пока спеки обрабатывают свои expect'ы, в тот же момент html-шаблон директивы еще не успевает закончить снятие 'fixed' и '-99999px', и убирание сверху или снизу item'ов.

Пока что для удобства каждый it закомментировал. Можно раскомментить какой-либо один и посмотреть как он работает. В общем пока есть два направления для работы:
1. Сделать так, чтобы каждый it стартовал с изначальным состоянием директивы и тестового компонента.
2. Сделать так, чтобы expect'ы отрабатывали исключительно после конца всех манипуляций.
3. И мелочь, но все же сейчас в браузере console.log отрабатывают без точного указания места, где они были вызваны. То есть перед каждым console.log стоит строка - 'context.ts:243'. Этот момент надо чинить?

**Comment by dyuv-dev** [comment]
@dhilt И отходя от темы тестов, хочется сказать о небольших наблюдениях - о том, как сейчас работает директива (не в тестах, а просто при npm start).
1. В Chrome при зажатии колесика мыши и дальнейшем движении вверх, либо вниз обновление item'ов срабатывает лишь один раз. Допустим, зажали колесико, потянули вверх - в итоге получили единожды 5 items и дальнейшего движения вверх или вниз не происходит. Но при этом иконка зажатого колесика остается.
2. В FF же с зажатым колесиком можно сколько угодно двигаться вниз. Но движение вверх удается лишь единожды, и при этом иконка колесика пропадает.

**Comment by dhilt** [comment]
@khajjit Отлично! я обязательно вольюсь в эти дела, как только заведу Workflow хотя бы на черно. В Карме есть beforeRun или что-то вроде этого (в общем, инструкции, которые выполняются перед каждым тестом), загони полную переинициализацию туда.

Суть обычного теста на скролл такая: отрендерелись, сделали 1 скролл в самый низ/верх, и посмотрели какой элемент в самом верху/низу соответственно. Потом по несколько скроллов туда-сюда, смотрим граничные элементы. Они должны соответствовать параметрическим расчетам, основанным на bufferSize и реальной высоте viewport.

Другой тип тестов на clip: отскроллились в одном направлении, поехали в другое, элементы на предыдущем направлении удалились, а padding-элемент нарастился так, что его высота компенсировала высоту удаленных элементов. И мы считаем, сколько элементов удалилось и все ли окей с padding-элементом.

На счет проблемы с Хромом, мне известно это issue, я даже сподобился пару лет назад сделать bug report в Chromium – https://bugs.chromium.org/p/chromium/issues/detail?id=493078... Ты мог бы попробовать написать им еще один баг (без упоминания моего), сделав свое репро и упор на историю с колесиком. Это будет полезно для тебя, а также должно повысить внимание к проблеме со стороны Хрома. Но имей в виду, может быть непросто доказать им, что это баг (это следует из истории моего репорта).

**Comment by dyuv-dev** [comment]
@dhilt Наверное все же имеете ввиду beforeEach? Он и обозначает конструкции, которые идут перед каждым тестом. И несмотря на то, что он сейчас есть в тестах, происходит беспорядок. В общем, я пока думаю-размышляю над правильным запуском тестов. Как всё починю, так начну писать тесты в описанных двух направлениях - ибо сейчас это проблемно и тесты не до конца отражают в действительности то, что должно быть в DOM.

Баг написать попробую. Можно за идею взять ваше репро? Только удаление элемента заменю переименованием элемента - попробовал, так баг тоже проявляется. Ну и может некоторые места переименую, чтобы были отличия.

**Comment by dhilt** [comment]
@khajjit Возможно, проблема с Кармой в том, что тесты должны быть асинхронными. DOM меняется поэтапно с задержками на fetch и render при каждом новом событии скролла (и при начальной загрузке). Попробуй покапать в сторону явной асинхронности тестов.

Бери мое репро, но лучше написать свое с нуля. Хорошо, если оно будет лаконичнее. Но главное, чтобы это было другое репро (с другим адресом). Пошли мне ссылку перед публикацией, я сделаю review.

Я дошел до 50% базового функционала в бранче [workflow-2](https://github.com/dhilt/ngx-ui-scroll/tree/workflow-2). Структура уже претерпела довольно большие изменения. Я ввел молчаливое понятие viewport, вынеся стили из UiScrollComponent в App – это принципиальный момент для тестов. Может быть, имеет смысл попытаться сделать мерж workflow-2 в твой тестовый бранч. Там работает начальная загрузка и почти работает скролл без обрезки. То есть можно будет писать тесты, покрывающие начальную загрузку. И там масса тестов может быть написана: в зависимости от размера viewport и размера bufferSize происходит столько-то вызовов datasource.get, видны такие-то элементы...

**Comment by dyuv-dev** [comment]
@dhilt Да, только в сторону асинхронности и копаю пока что.

Тем временем подскопировал репро на свой лад - https://jsfiddle.net/khajjit/yy89573b/.

**Comment by dhilt** [comment]
@khajjit я сделал форк и внес коррективы: https://jsfiddle.net/dhilt/hmoajo3c/1/ – повтори это демо на новом адресе и можно делать репорт. Очень здорово, что ты расширил сценарий, найдя случай с изменением содержимого. Вот это уже квази-баг Хрома. А если вместо innerHTML, скажем, класс поменять динамически? или handler новый добавить?

**Comment by dyuv-dev** [comment]
@dhilt Ну я написал в общем - https://bugs.chromium.org/p/chromium/issues/detail?id=807689.
И что удивительно, перед тем как начать писать репорт, внезапно репро заработало. Около 10 проходов подряд удались, но далее снова все пошло наперекосяк. Я в общем еще немного поскроллил и пришел к выводу, что приблизительно один раз из десяти скроллинг может и сработать, и упомянул об этом в репорте.

**Comment by dyuv-dev** [comment]
@dhilt Кажется наконец-то получилось заставить работать тесты. Правда почему именно они теперь работают корректно (надеюсь что правда корректно), я объяснить никак не смогу. Чем больше изучаю этот вопрос, тем все становится непонятнее.. Вот коммит - https://github.com/khajjit/ngx-ui-scroll/commit/fd55ddffe156c4568274c22a9426f27c5caa280f. И там есть небольшие изменения по файловой структуре, перенес spec.bundle.js в ./tests/helpers/entry-files.js и переименовал спеку как common.spec.js.

Пока что пришел к выводу, что следующий код способен корректно показывать DOM после изменений сделанных скроллингом:
```
it('should do something correctly...', fakeAsync(() => {
  // ...some actions on component
  fixture.whenStable().then(() => {
    fixture.detectChanges();
    tick(25);
    fixture.detectChanges();
    // ...here tests
  });
});
```
Вот только с точки зрения документации это бессмыслица полнейшая. Promise от fixture.whenStable() должен участвовать только в it, описанного как `it('...', async(() => {}));`, то есть с async. А функция tick предназначается исключительно для fakeAsync. В моем случае, я это все запихал в одну кучу, и по каким-то непонятным причинам всё заработало. В общем, не знаю что там происходит на самом деле в тестах, но работают они сейчас корректно, вот.

**Comment by dyuv-dev** [comment]
@dhilt И еще была проблема с тем, что каждый последующий it в тестах тащил за собой результаты предыдущего (на ngOnInit скроллер уже имел непустой массив элементов) и выходил бардак. Временно я его убрал довольно простым образом - https://github.com/khajjit/ngx-ui-scroll/commit/fd55ddffe156c4568274c22a9426f27c5caa280f#diff-e6b6672e919417b12e01d94c36deb965R33.
И что-то я вот подумал, а не проблема ли в самом скроллере? На ngOnDestroy массив items не зачищается, следовательно возможна следующая ситуация. Допустим, есть пользовательское приложение с двумя роутами и соответственно двумя компонентами, по одному на роут. Открываем первый роут со скроллером, в исходниках проходит инициализация, в Data.items появляются элементы, все замечательно. Переходим на другой роут, первый компонент завершает свое существование, скроллер соответственно тоже. На втором роуте при инициализации второго компонента скроллер инициализируется во второй раз, но в нем ведь по идее остаются items после первого роута и это неправильно?
И вроде бы грубая строчка `Data.items = [];` на ngOnInit предопределяет верное поведение скроллера, то есть при инициализации скроллера Data.items точно не имеет в себе элементов.

**Comment by dyuv-dev** [comment]
@dhilt Ну и теперь вероятно можно пробовать мержить код из бранча `workflow-2`? Или же лучше попытаться еще спеки порасписывать?

**Comment by dhilt** [comment]
@khajjit Проблема зачистки массива items лежит в плоскости трактовки сущности Data как singleton на уровне UiScrollModule в первой версии workflow. Это, конечно, неверная концепция и workflow-2 этой проблемы не имеет; там items принадлежат UiScrollComponent (а точнее, инстансу Workflow, который инициализируется во время инициализации Компонента через еще один слой WorkflowRunner) и не выходят за его пределы. Разрушение UIScrollComponent автоматически разрушает items. Инициализация сопровождается выставлением items в значение []. Таким образом, ты действительно раскопал причину твоих проблем с items, но при этом это была условно лишняя работа, т.к. wf-2 покрывает описанный тобой case. Мержить wf-2 стоило на более ранних этапах, но тем не менее и сейчас это не поздно сделать. 

Прямо сейчас идет работа по стабилизации геометрических расчетов, у нас есть проблемы с обработкой множественных событий скролла, но базовые сценарии отрабатывают, как надо. Их можно покрывать тестами набело.

Я надеюсь добраться в скором времени до тестов, меня немного пугает твой отчет по fixture-tick... У нас следующие асинхронности: событие/события скролла и циклы workflow. Последние разбиваются на асинхронные fetch и аснихронные render. 1 render занимает 1 event loop cycle (через нулевой settimeout), fetch зависит от datasource и потенциально может занимать произвольное время, но для тестов его тоже можно упростить до нулевого settimeout. Мы можем вывести наружу из скроллера какие-нибудь Promises/Observables, чтобы цепляться за них в тестах, например, событие завершения очередного цикла workflow. В wf-2 инстанциируется WorkflowRunner, который виден в Компоненте. Он может выдавать workflow.resolver наружу или весь workflow целиком, если мы захотим.

**Comment by dhilt** [comment]
@khajjit Мы подошли к моменту, когда нам нужны первые тесты. Того, что ты написал в первой спеке уже достаточно для текущих нужд. Нам нужен мерж wf-2 в твой бранч и pr на оригинальный репозиторий. Кроме этого я предлагаю наглядным образом объединить наши усилия, для этого я создам чат в скайпе. Если у тебя есть возражения против скайпа, то давай их обсуждать и искать альтернативу (нам нужно иметь возможность переписываться, созваниваться и шарить экран более, чем на 2 человек). Будем пытаться организоваться на троих!

**Comment by dyuv-dev** [comment]
@dhilt Да, было бы здорово где-нибудь запрятать Promise в исходниках скроллера, но ведь таким образом это будет идти лишним грузом в скомпилированный пакет, что не есть хорошо, ведь так?
Но еще лучше, как мне кажется, было бы что-нибудь придумать с пропихиванием spyOn с объектами `ChangeDetectorRef`, `ElementRef`, `ViewContainerRef`. Возможно сейчас когда смержу бранчи и начну изучать все изменения в workflow-2, может что-то и получится придумать, более прозрачное.

И сейчас когда буду сливать бранчи, есть высокая вероятность что тесты не заработают и придется еще попыхтеть над этими асинхронностями. Если не заработают, все равно PR открывать?

Насчет скайпа возражений нет, с этим все здорово.

**Comment by dhilt** [comment]
@khajjit Да, открывай PR в любом случае. Те комиты, которые ты будешь добавлять в свой бранч, будут автоматом попадать в PR до момента его приятия. Проблем с выводом наружу Promise/Observable нет. Компонент и так имеет инстанс WorkflowRunner, а при этом конечный программист не будет иметь к Компоненту доступа.

В общем, можешь попробовать сделать публичным свойство UiScrollComponent.workflowRunner, далее сделать публичным WorkflowRunner.workflow и поиграть в тестах с объектом UiScrollComponent.workflowRunner.workflow. И в частности с UiScrollComponent.workflowRunner.workflow.resolver, который сообщает о завершении цикла workflow. С этим нам вообще может не понадобиться spy, будем считать чистые циклы (Workflow.count) и запускать проверки при нужных нам значениях счетчика.

Тесты нужно будет немного подправить. Например, 90 индекс больше не является стартовым.

Скайп... зайди туда, скажи "привет". Я с Сашей сейчас ежедневно созваниваюсь, мы могли бы попробовать проводить расширенные встречи. Делегировать друг другу задачи... В общем, надо пробовать.

**Comment by dyuv-dev** [comment]
@dhilt В скайп зашел, о теме с кроссбраузерностью написал.

**Comment by dyuv-dev** [comment]
@dhilt Немного туплю насчет того, как бы смержить это все дело. Следующая тактика будет верной?
1. Залить изменения в бранче master из основного репозитория в мой форк.
2. Далее в форке создать бранч workflow-2 и залить туда изменения из основного репо.
3. Смержить изменения из workflow-2 в tests.
4. И открыть PR... только на какой бранч, на workflow-2?

**Comment by dhilt** [comment]
@khajjit Порядок я видел такой:

1. Update fork "tests" branch from original "workflow-2" branch via merge (not PR)
git checkout tests
git fetch upstream
git merge upstream/workflow-2
2. Resolve conflicts (manual)
3. Push merge commit to fork repository on the GitHub
4. Open PR from "tests" branch to original "master"

**Comment by dyuv-dev** [comment]
@dhilt Ну, я уже все сделал. В ручную правда, без возможностей от git. Сначала залил изменения из мастера, затем из wf-2, далее одним коммитом убрал конфликт (который сам сделал вчера) и открыл PR. Только вот на какой бранч открывать надо было, на wf-2 ведь?

**Comment by dhilt** [comment]
@khajjit Без разницы, можно и на мастер было. Но пусть остается так. Посмотри https://stackoverflow.com/a/19506355/3211932 – я бы делал это так.

**Comment by dyuv-dev** [comment]
@dhilt Ну, как и следовало ожидать, тесты работают сейчас неадекватно. Где сейчас работать над этим вопросом, всё также в форке?
И небольшой вопрос - наверное надо бы добавить FF и IE для тестов?

**Comment by dhilt** [comment]
@khajjit Переходи в оригинальный репозиторий, переключайся в workflow-2 и попробуем совместными усилиями довести его мержа с мастером. Сегодня я планирую сделать этот мерж, новые PR из твоего форка будет слишком долго делать, комить прямо в workflow-2, мы не будем друг другу мешать. После мержа опять разбежимся по бранчам и форкам.

**Comment by dhilt** [comment]
Я хочу получить работоспособный "мастер" с тестами, от которого Саша мог бы завтра начать плясать в сторону кроссбраузерности. Для этого давай допиливать workflow-2 совместными усилиями.

**Comment by dyuv-dev** [comment]
@dhilt Хорошо, буду делать коммиты в основной репо. Если я буду один делать изменения в ./tests, то да, мешать друг другу не будем.

**Comment by dyuv-dev** [comment]
Сейчас добавлю firefox и ie в конфиг кармы. Далее начну пытаться починить тесты, если не получится, то отпишусь и так сказать передам эстафету.

**Comment by dyuv-dev** [comment]
@dhilt Было довольно непросто догадаться, но основной момент почему упали сразу все спеки - это то, что исчезли стили для тега ui-scroll из ./src. Первые три спеки заработали корректно полностью, у четвертой возник момент с асинхронностью, там не успевают исчезнуть 'fixed' и '-99999px' с пяти верхних элементов.
И насчет последних двух еще предстоит подумать, как именно инициировать с новым кодом в исходниках событие скролла, но с этим наверное особых сложностей не должно быть. А вот что там будет с дополнительной асинхронностью и как починить все expect'ы, тут я скорее всего уже буду бессилен.

**Comment by dyuv-dev** [comment]
@dhilt Как инициировать скроллинг вверх/вниз понял, только вот нормально ли это, что обработчик скроллинга теперь висит не на теге ui-scroll, а на родительском?
Сделал маленький коммит - https://github.com/dhilt/ngx-ui-scroll/commit/2fe644a68d82ac6fec98889c0e4e9c01bc58fba5.
Скроллинг до конца правда не срабатывает, опять же скорее всего из-за новой асинхронности.

И еще есть такой вопрос. А как сейчас должен срабатывать скроллинг? Как раньше, полоса прокрутки доходит до самой конечной границы и мы получаем пять элементов или же теперь элементы подкачиваются, еще не доходя до границы?

Я еще попробую посмотреть что можно сделать с этими ошибками, но поскольку я уже наверное неделю как не могу уловить суть, точно ничего не выйдет. В общем больше коммитов не будет, передаю эстафету, вот.

**Comment by dhilt** [comment]
@khajjit Отвечая на вопрос о скроллинге, это и есть по сути workflow, то есть можно уже смело смотреть на имплементацию. И глядя на shouldFetchByDirection (процедура, отвечающая за начало процесса fetch), ты увидишь, что условием fetch теперь является неравенство itemEdge < viewportLimit (или itemEdge > viewportLimit), где itemEdge - край последнего (первого) видимого ряда, а viewportLimit - верхний (нижний) предел viewport, формирующийся методом Viewport.getLimit() из размера viewport + дельта. Это дельта - Settings.padding, помноженный на размер viewport. Таким образом, в случае Settings.padding = 0.5, условие подгрузки – это вылет краевого ряда за полторы высоты viewport.

**Comment by dhilt** [comment]
@khajjit Я сейчас допиливаю соответствие поведения старой версии, что я упоминал в скайпе, после этого готов буду вторгаться в тесты. Возможно, это произойдет уже завтра, но пока я продвигаюсь.

И да, мне пришлось ввести понятие viewport, это родительский элемент, он доступен через Workflow.viewport.scrollable. Это контейнер, который висит снаружи, он определяется приложением. В нашем App, это `<div class="viewport">`. И именно на нем отрабатывают события скролла, ты все правильно понял.

**Comment by dyuv-dev** [comment]
@dhilt Хмм, если условие подгрузки изменилось, надо две последние две спеки подогнать под эти условия - то есть сдвигать ползунок ровно на столько пикселей, сколько нужно для одной подгрузки нового элемента. А не в упор к самому верху/низу, как это сделано сейчас.

Касательно ошибок с асинхронностями так и не вышло ничего.
